import "./ts/index.ts";
require("./style/index.css");
require("./style/app.css");
require("./style/index.less");
require("./style/index.scss");
require("./style/index.postcss");
const h2 = document.createElement("h2");
h2.className = "test";
h2.innerHTML = "test";
document.body.append(h2);
